src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $illustration;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Subtitle;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isBest;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getIllustration(): ?string
    {
        return $this->illustration;
    }

    public function setIllustration(string $illustration): self
    {
        $this->illustration = $illustration;

        return $this;
    }

    public function getSubtitle(): ?string
    {
        return $this->Subtitle;
    }

    public function setSubtitle(string $Subtitle): self
    {
        $this->Subtitle = $Subtitle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getIsBest(): ?bool
    {
        return $this->isBest;
    }

    public function setIsBest(bool $isBest): self
    {
        $this->isBest = $isBest;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Classe\Cart;
use App\Entity\Product;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CartController extends AbstractController
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager) {
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/mon-panier", name="cart")
     */
    public function index(Cart $cart): Response
    {
        return $this->render('cart/index.html.twig', [
            'cart' => $cart->getFull()
        ]);
    }

    /**
     * @Route("/cart/add/{id}", name="add_to_cart")
     */
    public function add(Cart $cart, $id): Response
    {
        $cart->add($id);

        return $this->redirectToRoute('cart');
    }

    /**
     * @Route("/cart/remove", name="remove_my_cart")
     */
    public function remove(Cart $cart): Response
    {
        $cart->remove();

        return $this->redirectToRoute('products');
    }

    /**
     * @Route("/cart/delete/{id}", name="delete_to_cart")
     */
    public function delete(Cart $cart, $id): Response
    {
        $cart->delete($id);

        return $this->redirectToRoute('cart');
    }

    /**
     * @Route("/cart/decrease/{id}", name="decrease_to_cart")
     */
    public function decrease(Cart $cart, $id): Response
    {
        $cart->decrease($id);

        return $this->redirectToRoute('cart');
    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Panier - La Boutique Française{% endblock %}

{% block content %}
  <h1>Mon panier</h1>
  Retrouver l'ensemble des produits que vous avez ajouté à votre panier.

  {% if cart|length > 0 %}
    <table class="table table-hover table-dark mt-3">
      <thead>
        <tr>
          <th scope="col">Produits</th>
          <th scope="col"></th>
          <th scope="col">Quantité</th>
          <th scope="col">Prix</th>
          <th scope="col">Total</th>
        </tr>
      </thead>
      <tbody>
      {% set total = null %}
      {% for product in cart %}
        <tr>
          <td>
            <img src="/uploads/{{ product.product.illustration }}" alt="{{ product.product.name }}" height="50px">
          </td>
          <td>
            {{ product.product.name }} <br>
            <small>{{ product.product.subtitle }}</small>
          </td>
          <td>
            <a href="{{ path('decrease_to_cart', {'id' : product.product.id }) }}">
              <img src="{{ asset('assets/img/minus.png') }}" height="15px" alt="Retirer du panier">
            </a>
            x {{ product.quantity }}
            <a href="{{ path('add_to_cart', {'id' : product.product.id }) }}">
              <img src="{{ asset('assets/img/plus.png') }}" height="15px" alt="Ajouter au panier">
            </a>
          </td>
          <td>{{ (product.product.price / 100) |number_format(2, ',', '.') }} €</td>
          <td>{{ (product.product.price * product.quantity / 100) |number_format(2, ',', '.') }} €</td>
          <td>
            <a href="{{ path('delete_to_cart', {'id' : product.product.id }) }}">
              <img src="{{ asset('assets/img/delete.png') }}" height="20px" alt="Suprimer mon panier">
            </a>
          </td>
        </tr>
        {% set total = total + (product.product.price * product.quantity) %}
        {% endfor %}
      </tbody>
    </table>
    <div class="text-right mt-5">
      <b>Nombre de produit :</b> {{ cart|length }} <br>
      <b>Total de mon panier :</b> {{ (total / 100) |number_format(2, ',', '.') }} €
      <a href="{{ path('order') }}" class="btn btn-success btn-block">Valider mon panier</a>
    </div>
  {% else %}
  <hr>
  Votre panier est vide.
  {% endif %}
{% endblock %}